# Generated by Django 5.2.4 on 2025-07-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
