# Generated by Django 5.2.4 on 2025-08-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_category_options_product_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image1',
        ),
    ]
