# Generated by Django 5.2.4 on 2025-08-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
