# Generated by Django 5.2.4 on 2025-08-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_product_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description3',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description4',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
