# Generated by Django 5.2.4 on 2025-08-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_product_description3_product_description4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='header',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
