# Generated by Django 5.2.4 on 2025-09-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_product_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
