# Generated by Django 5.2.4 on 2025-09-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Comment',
        ),
    ]
