# Generated by Django 5.2.4 on 2025-09-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_rename_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
