# Generated by Django 5.2.4 on 2025-09-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_alter_comment_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='message',
        ),
    ]
