# Generated by Django 5.2.4 on 2025-09-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_alter_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
    ]
