# Generated by Django 5.2.4 on 2025-09-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_remove_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.CharField(blank=True),
        ),
    ]
