# Generated by Django 5.2.4 on 2025-09-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_comment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='comments',
        ),
    ]
