# Generated by Django 5.2.4 on 2025-09-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_rename_message_comment_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='phone',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
