# Generated by Django 5.2.4 on 2025-09-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_remove_comment_phone_alter_comment_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.CharField(blank=True),
        ),
    ]
