# Generated by Django 5.2.4 on 2025-09-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_remove_comment_comments_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.CharField(max_length=200),
        ),
    ]
