# Generated by Django 5.2.4 on 2025-09-22 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_alter_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='talk',
        ),
    ]
