# Generated by Django 5.2.4 on 2025-09-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_rename_reply_comment_talk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='talk',
        ),
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
