# Generated by Django 5.2.4 on 2025-09-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_alter_comment_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='phone',
            new_name='reply',
        ),
    ]
