# Generated by Django 5.2.4 on 2025-09-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_rename_phone_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.CharField(blank=True),
        ),
    ]
