# Generated by Django 5.2.4 on 2025-09-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0028_alter_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='phone',
        ),
    ]
