# Generated by Django 5.2.4 on 2025-09-23 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0029_rename_reply_comment_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='phone',
            new_name='description5',
        ),
    ]
