# Generated by Django 5.2.4 on 2025-09-23 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0030_rename_phone_comment_description5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description5',
            new_name='reply',
        ),
    ]
