# Generated by Django 5.2.4 on 2025-09-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_rename_description5_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='description',
        ),
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
