# Generated by Django 5.2.4 on 2025-09-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0032_rename_reply_comment_description_comment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='description',
        ),
        migrations.AlterField(
            model_name='comment',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
