# Generated by Django 5.2.4 on 2025-09-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0033_remove_comment_description_alter_comment_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
