# Generated by Django 5.2.4 on 2026-08-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0035_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='app_store_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.FileField(blank=True, null=True, upload_to='uploads/product/'),
        ),
    ]
